### ISSUE TITLE
Feature: transition on language toggle switch

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#101]
Op de `<a>` elementen, de geselecteerde en de optie, heb ik een view transition name gezet;

```html
			<a
				href="/en"
				on:click|preventDefault={() => changeLanguage('en')}
				class:active={$language === 'en'}
				title="Switch to English"
				style="view-transition-name: language-toggle-en;"
			>
```

de engelse opties hebben dezelfde name, en de franse opties hebben dezelfde name.

In de CSS heb ik dit toegevoegd:

```css
	::view-transition-old(root) {
		opacity: 0;
		translate: 0 20%;
		scale: 0.4;
	}

	::view-transition-new(root) {
		opacity: 1;
		translate: 0;
		scale: 1;
	}
```

Daarna in de `changeLanguage()` functie heb ik een `startViewTransition` gezet:
```js
	function changeLanguage(newLang) {
		const currentPath = $page.url.pathname.replace(/^\/[a-z]{2}/, ''); // Remove current language prefix
		const currentSearch = $page.url.search; // Keep query params

		document.startViewTransition(() => {
			// Navigate to the new language version of the current path
			goto(`/${newLang}${currentPath}${currentSearch}`);
			language.set(newLang); // Reactive store update
			localStorage.setItem('lang', newLang); // Optional if you want to persist language
		});
	}
```

## Demo

wowie amazing

https://github.com/user-attachments/assets/b7e04b85-5081-46a3-9642-d049e9744bf6
