### ISSUE TITLE
FIX: details marker on safari

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#109]
de originele `::marker` is op safari nog steeds zichtbaar, vgm doordat safari het marker pseudo element niet ondersteund (of partial support maar dan nog). 

fixen door de originele marker anders te stylen, of de nieuwe daar over heen te layeren?

**Comment by lisagjh** [comment]
```css
summary::-webkit-details-marker {   
    display:none; 
}
```
