### ISSUE TITLE
Feature: animate `<details>` on open/close

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#113]
`global.css`:
```css
  :root {
      interpolate-size: allow-keywords;
  }
```

`+page.svelte`:
```css
  details {
    height: 100%;
    transition: height .25s ease-in-out;
}

  details[open] {
    height: fit-content;
}
```

## Demo

Het gaat nog niet helemaal zoals ik wil. de andere details worden meteen gesloten, en ik wil eigenlijk ook dat die geanimeerd word. ook schiet de `height` een soort door, bij het sluiten word het element eerst even kleiner en dan weer de juiste grootte. 

https://github.com/user-attachments/assets/a1181b9a-ff9d-42dc-808e-08919e6621bb

## Oplossingen

- checkbox container in de details een height transition geven ook? 
- min-height op de gesloten details?

### Bron

Krijn stuurde dit artikel afgelopen week die ik ook in de css weekly had gezien!

https://css-tricks.com/using-styling-the-details-element/#aa-animate-the-opening-and-closing

<img width="713" alt="Image" src="https://github.com/user-attachments/assets/f9462caf-61bf-47fa-a850-5587a7ee2329" />
