### ISSUE TITLE
Feat: scroll-anim on detail page gallery

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#189]
Voeg een leuke scroll animatie toe op de gallery van de detail page

**Comment by lisagjh** [comment]
# Bouwen

Ik heb een simpele scroll animatie toegevoegd op de entry en exit van de figures. 

```css
@keyframes animate-in-and-out {
			entry 0% {
				opacity: 0.5;
				transform: translateY(50%);
			}
			entry 40% {
				opacity: 1;
				transform: translateY(0);
			}

			exit 60% {
				opacity: 1;
				transform: translateY(0);
			}
			exit 100% {
				opacity: 0.5;
				transform: translateY(-50%);
			}
		}

		li {
			animation: linear animate-in-and-out;
			animation-timeline: view();
		}
```

**Comment by lisagjh** [comment]
# Analyseren

ik had op de [scroll-driven-animations demo site](https://scroll-driven-animations.style/) een vet voorbeeld gezien, waarbij de image positie word aangepast bij het scrollen. Ik wil ook wel proberen zoiets te maken, maar ik weet niet zeker in hoeverre dit goed aansluit op de stijl en vibe van de rest van de site.

Dus we gaan het gewoon proberen :)

**Comment by lisagjh** [comment]
# Bouwen

Om de normale versie te behouden, gebruik ik een extra class op de `<ul>` om deze animatie tegen aan te bouwen.

Ik wrap dit alles eerst in een `@media prefers-reduced-motion` en `supports` query:

```css
@media (prefers-reduced-motion: no-preference) {
		@supports (animation-timeline: view()) {
```

Daarna geef ik de wrapper een andere layout, door `:has` te gebruiken:

```css
			.wrapper:has(.fancy) {
				justify-content: center;
				align-items: center;
				overflow: hidden;
				min-height: 70vh;
			}
```

En dan de nieuwe `ul.fancy` stylen:

```css
.gallery.fancy {
				display: flex;
				flex-direction: row;
				align-items: flex-start;
				justify-content: flex-start;
				gap: 5cqw;
				overflow-x: scroll;
				overflow-y: hidden;
				scroll-snap-type: x mandatory;
				scroll-behavior: smooth;
				padding: 0 2cqw;
				margin: 0;
			}
```

Hierbij gebruik ik `cqw` = 1% van een query container's width. 


En dan de styling van de `.gallery-item`'s en de imgs:

```css
.fancy .gallery-item {
				display: flex;
				flex-direction: column;
				align-items: start;
				justify-content: start;
				width: 100%;
				min-width: 50cqw;
				scroll-snap-align: center;
			}

			.fancy .gallery-item img {
				height: 50cqh;
				min-width: 80%;

				object-fit: cover;
				object-position: 100% 0;
			}
```

Hierbij gebruik ik `50cqh` om te zorgen dat de afbeeldingen minstens de helft van de hoogte van de container innemen.



Daarna eindelijk de animatie:

```css
			.@keyframes adjust-image {
				0% {
					object-position: 100% 0;
				}
				100% {
					object-position: 0 0;
				}
			}

			.fancy .gallery-item img {
				animation: adjust-image linear both;
				animation-timeline: view(x);
			}
```

Door op de `animation-timeline: view(x);` te gebruiken, word alleen naar de `x-as` gekeken.

## Demo

En dan is dit het resultaat:

https://github.com/user-attachments/assets/9546df2d-5845-4b1c-a8b5-f03f966b5b9e

**Comment by lisagjh** [comment]
# inverted border radius

Toen dit af was, wilde ik nog wat leukers doen met de figcaption. 

## Analyseren

Ik wil deze over de figure heen positioneren, en dan met een `::before` en `::after` zo een inverted border-radius te geven. Alleen geen idee hoe.


## Ontwerpen

Ik heb een kleine schets gemaakt om beetje te ontdekken hoe dit zou moeten werken.

![Image](https://github.com/user-attachments/assets/9f93d73e-709f-4074-ac33-ae8e6214331b)

---

Via google ben ik [dit artikel](https://itnext.io/how-to-make-a-fancy-inverted-border-radius-in-css-5db048a53f95) tegen gekomen. Super duidelijke tutorial die stap voor stap laat zien en uitlegt wat er gebeurt. 
Hieruit heb ik een paar notities bij de schets gezet, zoals je ziet.


## Bouwen

```css
	/* fancy gallery w fancy figcaption */
	.fancy .gallery-item figcaption {
		border-radius: 0 4px 0 0;
		transform: translateY(-100%);
		padding: 3% 4%;
	}

	.gallery-item figcaption::before {
		content: '';
		position: absolute;
		left: 0;
		top: -1rem;
		height: 1rem;
		width: 1rem;
		border-top-left-radius: 25px;
		border-radius: 0 0 0 8px;
		box-shadow: 0 10px 0 0 var(--off-white);
	}

	.gallery-item figcaption::after {
		content: '';
		position: absolute;
		right: -1rem;
		bottom: 0.4rem;
		height: 1rem;
		width: 1rem;
		border-top-left-radius: 25px;
		border-radius: 0 0 0 8px;
		box-shadow: 0 10px 0 0 var(--off-white);
	}
```

### Resultaat

<img width="372" alt="Image" src="https://github.com/user-attachments/assets/775427d9-0e9b-4a7c-a4ae-ddee3bfbdab5" />


**Bron**

- [how to make a fancy inverted border radius in css](https://itnext.io/how-to-make-a-fancy-inverted-border-radius-in-css-5db048a53f95)
