### ISSUE TITLE
Prijs filter: suggesties styling

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#198]

**Comment by lisagjh** [comment]
# Ontwerpen

Ik wilde duidelijk maken dat de suggesties bij de min of de max input horen.

Hiervoor heb ik schetsen gemaakt.

> SCHETSEN INVOEGEN

**Comment by lisagjh** [comment]
# Bouwen

**Gesloten**
<img width="355" alt="Image" src="https://github.com/user-attachments/assets/3d7b519f-b6be-4732-9b81-c41c9e09cfc5" />

**Open**
<img width="337" alt="Image" src="https://github.com/user-attachments/assets/16ccd9cb-01ed-46f6-8491-ca891465a1da" />

---

Om wanneer de suggestions geopend zijn het te laten lijken alsof de suggesties en de input een ding zijn,  `:has` gebruikt.

```css
.price-input:has(.suggestion-buttons) input {
    border-bottom: 0;
    border-radius: var(--radius-one) var(--radius-one) 0 0;
}
```

Omdat de `.suggestion-buttons` alleen gerendered worden wanner `showMin = true`, bevat de parent div deze ook alleen wanneer dat zo is. Hierdoor is dit een goed gebruik van `:has`.
