### ISSUE TITLE
SIH - improve search functionality to display card previews

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#281]
verbeter de zoek functionaliteit door een aantal "product" cards te tonen (als preview, compact view enz). 

- [x] dynamisch geupdate "preview" box ?
- [x] aantal resultaten bij zoekterm
- [ ] ... ?

**Comment by lisagjh** [comment]
# vind matchende zoekresultaten

## schets

Ik ben begonnen met een schets maken, van hoe de search result preview module er uit gaat zien en wat pseudo code van hoe het moet werken!

+ standaard `position: absolute; bottom: 0;` gebruiken. wanneer supported, anchor positioning. bc live laugh love anchor positioning. dan weet ik zeker dat het element goed aan de input blijft zitten.

![Image](https://github.com/user-attachments/assets/b9123576-1d48-42c9-8cfa-4b70e9de4a61)

## get search results 

toen heb ik de JS gemaakt! en bedacht ik me dat dit niet nodig is. want in `applyFilters` word al op zoekterm gefiltered. maar misschien toch apart doen? brb ik ga wat proberen en kijken wat werkt

```js
// search module: display search results previews below search bar
const searchBar = document.querySelector('#zoeken');

searchBar.addEventListener('input', function() {
    const searchTerm = this.value;
    const searchResults = searchModule(searchTerm);
})

function searchModule(searchTerm) {
    const searchResults = [];
    for (const item of Object.values(tabFilteredListings)) {
        if (item.naam.toLowerCase().includes(searchTerm.toLowerCase())) {
            searchResults.push(item);
        }
    }
    console.log("SEARCH RESULTS", searchResults);
    return searchResults;
}
```

**Comment by lisagjh** [comment]
# preview module

toch apart gedaan, werkt iets fijner, plus separation of concerns i guess? maar V1 werkt!

+ nu functionality dat je op de naam kan klikken en dat dat de zoekterm word. ik denk niet dat dit gebruikt gaat worden, maar maybe leuk voor een feature waar je kan kiezen om op een specifieke sport te zoeken? zoals balsport, voetbal, handbal, zwemmen, paardrijden, weet ik veel wat! 

## alle code so far

```js
// ** search module preview functionality **
document.querySelector('#zoeken').addEventListener('input', function() {
    const searchTerm = this.value.toLowerCase();
    showSearchPreview(searchTerm);
});

function showSearchPreview(searchTerm) {
    const previewContainer = document.querySelector('.search-preview');
    previewContainer.innerHTML = '';

    // empty array to store all search results
    const searchResults = [];

    Object.values(allListings).forEach(item => {
        const nameMatches = item.naam?.toLowerCase().includes(searchTerm);
        const mainCatMatches = item.main_category?.toLowerCase().includes(searchTerm);
        const subcatMatches = item.subcategories?.some(sub => sub.toLowerCase().includes(searchTerm));
        const locationMatches = (
            item.address?.city?.toLowerCase().includes(searchTerm) ||
            item.address?.district?.toLowerCase().includes(searchTerm) ||
            item.address?.house_number?.toLowerCase().includes(searchTerm) ||
            item.address?.neighborhood?.toLowerCase().includes(searchTerm) ||
            item.address?.postal_code?.toLowerCase().includes(searchTerm) ||
            item.address?.street?.toLowerCase().includes(searchTerm)
        );

        if (nameMatches || mainCatMatches || subcatMatches || locationMatches) {
            searchResults.push(item);
        }
    })

    console.log("SEARCH RESULTS ARRAY", searchResults);

    if (searchResults.length === 0) {
        container.innerHTML = '<div class="px-4 py-2 text-sm text-gray-500">Geen resultaten</div>';
        container.style.display = 'block';
    }

    searchResults.slice(0, 10).forEach(item => {
        const div = document.createElement('div');
        div.className = 'px-4 py-2 hover:bg-gray-100 cursor-pointer border-b last:border-b-0';
        div.textContent = item.naam;
        div.addEventListener('click', () => {
            document.querySelector('#zoeken').value = item.naam;
            container.style.display = 'none';
            applyFilters(true);
        });
        previewContainer.appendChild(div);
    })

    previewContainer.style.display = 'block';
}

// search module close functionality
document.addEventListener('click', function(event) {
    const preview = document.querySelector('.search-preview');
    const input = document.querySelector('#zoeken');

    if (!preview.contains(event.target) && event.target !== input) {
        preview.style.display = 'none';
    }
});
document.querySelector('#zoeken').addEventListener('blur', function() {
    setTimeout(() => {
        document.querySelector('.search-preview').style.display = 'none';
    }, 150); // geeft gebruikers tijd om op een resultaat te klikken
});
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        const preview = document.querySelector('.search-preview');
        if (preview) {
            preview.style.display = 'none';
        }
    }
});
```

### demo

kleine demo. 

https://github.com/user-attachments/assets/28d1c276-87dd-44ce-8c6c-a13a1a6f8dcb

**Comment by lisagjh** [comment]
# progresss

https://github.com/user-attachments/assets/c55ea942-749a-4e30-b5ec-c494d186b3d1

**Comment by lisagjh** [comment]
# styling wanneer results visible

moeilijk! ik heb het nu met CSS met `:focus-within` maar dit werkt niet optimaal. hoe ik het eerst deed met JS en tailwind was ook niet optimaal.

![Image](https://github.com/user-attachments/assets/937cf139-300c-434b-bdc8-46e48b42860b)
![Image](https://github.com/user-attachments/assets/42ce0da2-bcaa-4c7f-8bfc-ae54e4414793)

💡 idee: een .visible class toevoegen? waardoor in CSS de styling anders word?

**Comment by lisagjh** [comment]
</3

![Image](https://github.com/user-attachments/assets/97d82ea8-3e65-4f0f-b3b1-1f7ff22f487c)

**Comment by lisagjh** [comment]
# .visible 

Ik heb inderdaad de oplossing met een class toevoegen gebruikt, om te zorgen dat de cards container zichtbaar is op het juiste moment en dat de search container de juiste styling heeft op het juiste moment. Ik check dan met `:has(.visible)` of de container ergens die class bevat, en op die manier word die styling op dat moment aangepast.

Ik heb bij de CSS ook wat extra comments gezet, om dit duidelijk te maken voor de andere developers. 

```css
<style>
  /* styling before start searching */
  .search-preview {
      position: absolute;
      top: 3.25rem;
      width: 100%;
      height: fit-content;
      border-radius: 0 0 1.75rem 1.75rem;
      outline: none;
      overflow: hidden;
      z-index: 10;
      scrollbar-color: var(--blue-50) var(--blue-05);
      transform: scaleY(0.5);
      transform-origin: top center;
      opacity: 0;
      transition: .35s cubic-bezier(0.175, 0.885, 0.32, 1.275);
  }

  /* if a searchterm has been entered, make it visible + transition */
  .search-preview.visible {
      display: flex;
      transform: scaleY(1);
      opacity: 1;
      outline: 1px solid #ccc;
      margin-top: -0.1rem;
  }

  /* before searchterm has been entered */
  .search-container {
      border-radius: 1.75rem;
      width: 101%;
      outline: 1px solid #ccc;
      transition: .2s ease-in-out;
  }

  /* after searchterm has been entered and the preview is visible */
  .search-container:has(.visible) {
      border-radius: 1.75rem 1.75rem 0 0;
      border-bottom: none;
  }

  /* make the items snap to the center when scrolling */
  .card-container {
      scroll-behavior: smooth;
      scrollbar-width: none;
      scroll-snap-type: x mandatory;

      & li {
          scroll-snap-align: center;
      }
  }
```

## class toevoegen in JS

Ik heb op dezelfde plek als waar ik de functie aanroep de class toegevoegd aan de container.

```js
// ** search preview functionality **
document.querySelector('#zoeken').addEventListener('input', function() {
    const searchTerm = this.value.toLowerCase();
    const previewContainer = document.querySelector('.search-preview');

    if (searchTerm !== '') {
        previewContainer.classList.add('visible');
        showSearchPreview(searchTerm);
    } else {
        previewContainer.classList.remove('visible');
        previewContainer.innerHTML = ''; // leegmaken bij lege zoekterm
    }
});
```

En ik zorg ook dat de .visible weer word verwijderd wanneer de gebruiker buiten de container of op esc klikt

```js
 // search preview close functionality - close on click outside and close on escape
document.addEventListener('click', function(event) {
    const previewContainer = document.querySelector('.search-preview');
    const searchBar = document.querySelector('#zoeken');

    if (!previewContainer.contains(event.target) && event.target !== searchBar) {
        previewContainer.classList.remove('visible');
    }
});

document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        const previewContainer = document.querySelector('.search-preview');
        previewContainer.classList.remove('visible');
    }
});
```

---

### CSS carousels en anchor positioning

Daarna heb ik wat geëxperimenteerd met CSS carousels hier.

```css
 /* experimental CSS features, right now (may 2025) only supported in chrome and edge. --> css only carousel buttons, anchor positioning for buttons */
@supports (anchor-name: --foo) {
    #zoeken {
        anchor-name: --searchbar;
    }

    div.search-preview {
        position-anchor: --searchbar;
        top: anchor(--searchbar bottom);
        justify-self: anchor-center;

        padding-bottom: 2rem;
    }

    .card-container {
        position: relative;
        anchor-name: --container;
        width: 100%;

        &::scroll-button(*) {
            position: absolute;
            position-anchor: --container;
            top: calc(anchor(--container bottom) - .25rem);
            display: flex;
            justify-content: center;
            align-items: center;
            width: 2rem;
            height: 2rem;
            background-color: var(--blue-light);
            border: 1px solid var(--blue-50);
            border-radius: 50%;
            margin: -1rem 1.5rem;
            transition: .25s ease-in-out;
        }

    /* more code for the states and individual buttons here */
```

### full JS

```js
// ** search preview functionality **
document.querySelector('#zoeken').addEventListener('input', function() {
    const searchTerm = this.value.toLowerCase();
    const previewContainer = document.querySelector('.search-preview');

    if (searchTerm !== '') {
        previewContainer.classList.add('visible');
        showSearchPreview(searchTerm);
    } else {
        previewContainer.classList.remove('visible');
        previewContainer.innerHTML = ''; 
    }
});

function showSearchPreview(searchTerm) {
    const previewContainer = document.querySelector('.search-preview');
    previewContainer.innerHTML = '';

    // const cardContainer = document.querySelector('.card-container');
    const cardContainer = document.createElement('ul');
    cardContainer.className = 'card-container flex flex-row overflow-x-scroll gap-4 pb-4 pt-2';
    cardContainer.innerHTML = '';
    previewContainer.appendChild(cardContainer);

    // empty array to store all search results
    const searchResults = [];

    // check each listing for a match, add matching items to searchResults
    Object.values(allListings).forEach(item => {
        const nameMatches = item.naam?.toLowerCase().includes(searchTerm);
        const mainCatMatches = item.main_category?.toLowerCase().includes(searchTerm);
        const subcatMatches = item.subcategories?.some(sub => sub.toLowerCase().includes(searchTerm));
        const locationMatches = (
            item.address?.city?.toLowerCase().includes(searchTerm) ||
            item.address?.district?.toLowerCase().includes(searchTerm) ||
            item.address?.house_number?.toLowerCase().includes(searchTerm) ||
            item.address?.neighborhood?.toLowerCase().includes(searchTerm) ||
            item.address?.postal_code?.toLowerCase().includes(searchTerm) ||
            item.address?.street?.toLowerCase().includes(searchTerm)
        );

        if (nameMatches || mainCatMatches || subcatMatches || locationMatches) {
            searchResults.push(item);
        }
    })

    // if no results, display 'geen resultaten'
    if (searchResults.length === 0 && searchTerm !== '') {
        previewContainer.innerHTML = `
        <div>
            <p class="p-4 text-md">Geen resultaten</p>
        </div>
        `;
    }

    // display number of results
    const resultsLength = document.createElement('p');
    resultsLength.textContent = `${searchResults.length} Resultaten`;
    resultsLength.className = 'px-4 text-sm text-gray-500 w-fit';
    if (searchResults.length !== 0) {
        previewContainer.prepend(resultsLength);

    }

    // show only a maximum of the results
    searchResults.slice(0, 30).forEach(item => {
        const imgLink = item.image_url ? item.image_url : 'https://sportinhaarlem.dev.atlantisdigital.online/wp-content/uploads/2020/03/placeholder-1-jpg.avif';

        const card = document.createElement('li');
        card.className = 'preview-card flex flex-col justify-between text-left gap-1 p-4 hover:bg-gray-100 cursor-pointer border-b last:border-b-0 min-w-[200px] w-full rounded-md border border-gray-200';
        card.innerHTML = `
            <div class="flex flex-col gap-2">
                <img src="${imgLink}" alt="foto van ${item.naam}" class="h-24 w-full object-cover object-center select-none rounded-sm">

                <h3 class="leading-tight font-poppins capitalize"><b>${item.naam}</b></h3>
            </div>

            <button class="flex items-center gap-2 text-[#288024] border-t-0 border-x-0 border-b border-[#288024] w-fit p-1 cursor-pointer rounded-none bg-transparent hover:bg-transparent hover:text-[#288024] meer-informatie">
                    <svg width="10" height="13" viewBox="0 0 10 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                      ...
                    </svg>
                    <span class="sr-only">${item.naam}</span>
                    <span class="leading-[.5] font-roboto font-light select-none"> meer informatie</span>
                </button>                    
        `;
        cardContainer.appendChild(card);
    })

    const searchContainer = document.querySelector(".search-container");
    const searchBar = document.querySelector("#zoeken");
    searchContainer.classList.add('border-b-0', 'rounded-b-none');
    searchContainer.classList.add('rounded-[1.75rem]');
}

// search preview close functionality - close on click outside and close on escape
document.addEventListener('click', function(event) {
    const previewContainer = document.querySelector('.search-preview');
    const searchBar = document.querySelector('#zoeken');

    if (!previewContainer.contains(event.target) && event.target !== searchBar) {
        previewContainer.classList.remove('visible');
    }
});

document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        const previewContainer = document.querySelector('.search-preview');
        previewContainer.classList.remove('visible');
    }
});
```

**Comment by lisagjh** [comment]
# done

het werkt! alles werkt! 

## uitleg

Hier wordt de `scrollToCard()` function aangeroepen, en worden de naam van het item en tot welke tab het behoort mee gegeven als argumenten.

```js
   // listen for a click on the card - button doesnt work because its not in the DOM yet
            document.querySelector('.search-preview').addEventListener('click', function(e) {
                const button = e.target.closest('.card-button');
                if (button) {
                    const itemName = button.dataset.itemName;
                    const itemTab = button.dataset.mainTab;
                    scrollToCard(itemName, itemTab);
                }
            });
```

In de functie worden een paar stappen doorlopen.

1. vergelijk de actieve tab met de target tab van het item.
2. check of de card bestaat
3. scroll naar card

```js
function scrollToCard(itemName, targetTab) {
    // close the search preview
    const previewContainer = document.querySelector('.search-preview');
    previewContainer.classList.remove('visible');

    const url = new URL(window.location.href);
    const currentTab = url.searchParams.get('tab');

    // if the current tab is not the same as the target tab, switch to the right tab
    if (currentTab !== targetTab) {
        const tabButton = document.getElementById(`tab-${targetTab}`);
        if (tabButton) {
            tabButton.click();

            let retries = 0;
            const maxRetries = 5;

            function checkCard() {
                const targetCard = document.querySelector(`.listview-card[data-item-name="${itemName}"]`);
                if (targetCard) {
                    targetCard.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                    highlight(targetCard);
                } else if (retries < maxRetries) {
                    retries++;
                    setTimeout(checkCard, 150);
                } else {
                    console.warn(`Card "${itemName}" not found after switching to tab "${targetTab}".`);
                }
            };

            setTimeout(checkCard, 300);
        } else {
            console.warn(`Tab button for "${targetTab}" not found.`);
        }
    } else {
        // same tab - scroll to the target card
        const targetCard = document.querySelector(`.listview-card[data-item-name="${itemName}"]`);
        if (targetCard) {
            targetCard.scrollIntoView({
                behavior: 'smooth',
                block: 'start'
            });
            highlight(targetCard);
        } else {
            console.warn(`Card "${itemName}" not found in current tab "${currentTab}".`);
        }
    }
}
```

binnen de functie is een `checkCard` functie. Ik heb hier wat hulp van chatpgt bij gehad, omdat ik uren bezig geweest ben met het proberen te switchen van de tabs. Omdat het een naam heeft, kan hij zichzelf herkennen. Hierdoor kan de functie zichzelf opnieuw aanroepen met `setTimeout(checkCard, 150)`. De functie wacht 150ms en probeert het dan opnieuw. Dit is handig voor als de card nog niet in de pagina staat. Het zoeken naa de card word nu herhaald tot het lukt of het maximaal aantal pogingen is bereikt. Het is geen oneindige loop. Het herhaalt met pauzes. Dit lijkt op _polling_ waarbij je iets herhaaldelijk checkt tot het beschikbaar is, in dit geval de kaart in de DOM.

```js
 let retries = 0;
const maxRetries = 5;

function checkCard() {
    const targetCard = document.querySelector(`.listview-card[data-item-name="${itemName}"]`);
    if (targetCard) {
        targetCard.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
        });
        highlight(targetCard);
    } else if (retries < maxRetries) {
        retries++;
        setTimeout(checkCard, 150);
    } else {
        console.warn(`Card "${itemName}" not found after switching to tab "${targetTab}".`);
    }
};

setTimeout(checkCard, 300);
```

Als de gebruiker klikt op de button en naar de kaart wilt scrollen, word de `highlight()` functie aangeroepen.

```js
// to indicate to the user what card has been scrolled to, highlight it with an animation
function highlight(element) {
    // find the .info-container within the targetCard
    const infoContainer = element.querySelector('.info-container');

    //  highlight animation can be found at: /* card scroll highlight */
    if (infoContainer) {
        // add class for animation
        infoContainer.classList.add('pulse-highlight');

        // remove class after timeOut
        setTimeout(() => {
            infoContainer.classList.remove('pulse-highlight');
        }, 5000);
    }
}
``` 

En de CSS met de .pulse-highlight class:

```css
.listview-card:has(.pulse-highlight) {
    animation: pulse 1s ease-in-out 3 alternate-reverse;
    transition: .25s ease-in-out;
}

.pulse-highlight {
    animation: pulse-bg 1s ease-in-out 3 alternate-reverse;
}

@keyframes pulse {
    from {
        scale: 1;
    }

    to {
        scale: 1.02;
    }
}

@keyframes pulse-bg {
    from {
        background-color: var(--blue-10);
    }

    to {
        background-color: var(--blue-20);
    }
}
```

## demo

https://github.com/user-attachments/assets/380e1a5b-b272-49a4-afd6-165f36308bd4
