### ISSUE TITLE
Pleasurable: animatie op cards bij toepassen filters

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#80]
# Analyseren

Ik weet dat sveltekit ingebouwde animaties heeft, dingen zoals `fly` en `fade`. Dit lijkt mij de makkelijkste approach. 

Als dit niet werkt, dan wil ik view transitions toepassen. Ik had [deze demo](https://view-transitions.chrome.dev/) gezien, voornamelijk de cards demo. Zoiets vergelijkbaars kan ik hier ook doen.

# Ontwerpen

Wanneer de filters worden toegepast, faden de listings die niet van toepassing zijn weg, en worden ze kleiner. De listings die wel van toepassing zijn, animeren naar hun nieuwe plek op het scherm. Op deze manier is de overgang smoother.

In svelte animations wil ik hier fly en fade voor gebruiken.

--

Svelte animations werkt niet, dus view transitions it is. Ik kan hier dezelfde logica gebruiken als in de `layout` en die ik heb gebruikt bij de card naar de detail page.

# Bouwen

**1. view transition name toevoegen**

Op het `<li>` element van de listings, heb ik een `view-transition-name` toegevoegd. Deze moet uniek zijn.

```
<li style={`view-transition-name: listing-${listing.listingId};`}>
```

**2. CSS view transitions maken**

In de CSS, maak de view transitions.

```css
/* filtered listings view transitions */
	::view-transition-old(card) {
		animation: fadeOut 0.5s ease-in-out;
	}

	::view-transition-new(card) {
		animation: slideIn 0.5s ease-in-out;
	}

	@keyframes fadeOut {
		from {
			opacity: 1;
			transform: scale(1);
		}
		to {
			opacity: 0;
			transform: scale(0.5);
		}
	}

	@keyframes slideIn {
		from {
			opacity: 0;
			transform: translateY(-20%);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}
```

**3. Js start view transition**

Hier had ik wat issues mee.

Ik heb eerst de manier waarop de listings werden gefilterd, in een eigen functie gezet. Anders zou ik in `$effect` twee keer hetzelfde grote blok tekst hebben.

```js
// seperate function to filter the listings
	function filterFunction(listing) {
		// filter out listings that don't match the selected destination, capacity, bedrooms, or bathrooms
		let passesBasicFilters =
			(!selectedDestination || listing.location === selectedDestination) &&
			(!selectedCapacity || listing.capacity >= Number(selectedCapacity)) &&
			(selectedBedrooms === '7+'
				? listing.bedrooms >= 7
				: listing.bedrooms >= Number(selectedBedrooms)) &&
			(selectedBathrooms === '7+'
				? listing.bathrooms >= 7
				: listing.bathrooms >= Number(selectedBathrooms));

		// filter out listings that don't match the selected amenities
		// If amenities are selected, we check if the listing has any of the selected amenities
		// We use the spread operator to ensure that we're working with arrays
		let passesAmenitiesFilter = true;
		if (selectedAmenities.length > 0) {
			if (!listing.amenities || listing.amenities.length === 0) {
				// If the listing has no amenities, it doesn't match
				passesAmenitiesFilter = false;
			} else {
				// If the listing has amenities, we check if any of the selected amenities are included
				// We use the `includes` method to check if the selected amenities are in the listing's amenities array
				// We also use the spread operator to ensure that we're working with arrays
				const listingAmenityNames = listing.amenities.map((amenity) =>
					(typeof amenity.names === 'object'
						? amenity.names.en || amenity.names.fr
						: amenity.names
					).toLowerCase()
				);

				// Ensure any selected amenities exist in listing
				passesAmenitiesFilter = selectedAmenities.some((selectedAmenity) =>
					listingAmenityNames.includes(selectedAmenity.toLowerCase())
				);
			}
		}

		return passesBasicFilters && passesAmenitiesFilter;
	}

```

Daarna in `$effect`, deze functie aangeroepen en toegepast op de listings. Daarna binnen de logica om de view transitions te starten, word de filteredListings array gevuld met de gefilterde functies.

```js
	$effect(() => {
		const newFilteredListings = data.listingsData.filter(filterFunction);

		if (!document.startViewTransition) {
			filteredListings = newFilteredListings;
		} else {
			document.startViewTransition(() => {
				filteredListings = newFilteredListings;
			});
		}
	});
```
