### ISSUE TITLE
FIX: date picker in form

### ISSUE THREAD

**Issue by lisagjh** [lisagjh/i-love-web#85]
# Analyseren

In het originele ontwerp, heeft de date picker in de form voor de listings, een placeholder text. In eerste instantie heb ik dit geprobeerd na te bootsen door het een `type=text` te maken, en `onfocus` te veranderen naar een `type=date`. Dit werkt, maar is niet ideaal.

<img width="501" alt="Image" src="https://github.com/user-attachments/assets/ec33e6a0-f46d-436d-9c56-128bdeb7a987" />

```html
		<div class="date-picker">
				<input
					type="text"
					name="check-in"
					id="check-in"
					placeholder="Check-in"
					onfocus={(this.type = 'date')}
					onfocusout={(this.type = 'text')}
				/>
				<input
					type="text"
					name="check-out"
					id="check-out"
					placeholder="Check-out"
					onfocus={(this.type = 'date')}
					onfocusout={(this.type = 'text')}
				/>
		</div>
```

Ik heb het hier ook met Jason over gehad, en hij zei dat ik misschien beter een ander element er over heen kan leggen, en deze hiden op focus en wanneer een datum geselecteerd is.

# Schets

!! Invoegen

# Bouwen

Ik ben begonnen met de span over de input heen te positioneren.

```html
			<div class="date-picker">
				<div class="date-wrapper">
					<span>Check In</span>
					<input type="date" name="check-in" id="check-in" />
				</div>

				<div class="date-wrapper">
					<span>Check Out</span>
					<input type="date" name="check-out" id="check-out" />
				</div>
			</div>
```

```css
	.date-picker {
		display: flex;
		flex-direction: column;
		gap: 1rem;

		& input {
			width: 100%;
		}
	}

	.date-wrapper {
		position: relative;
		
		& span {
			background-color: var(--white);
			color: var(--grey);
			font-weight: 300;
			display: block;
			position: absolute;
			margin-top: 1rem;
			min-width: 8rem;
			margin-left: 0.5rem;
		}
	}

	@container form (width >= 23rem) {
		.date-picker {
			display: flex;
			flex-direction: row;
			gap: 0;
		}

		.date-wrapper {
			width: 100%;
		}

		.date-wrapper:first-of-type input {
			border-radius: var(--radius-one) 0 0 var(--radius-one);
			border-right: none;
			position: relative;
		}

		.date-wrapper:last-of-type input {
			border-radius: 0 var(--radius-one) var(--radius-one) 0;
			border-left: none;
		}

		.date-wrapper span {
			position: absolute;
			z-index: 10;
			min-width: 7rem;
		}
	}
```

Het hiden van de span op focus en input werkt alleen niet goed. Dus ik ga op zoek naar een andere oplossing.
